spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_admin?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ecommerce
    password: ecommerce123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect

services:
  customer-service: http://localhost:8081
  product-service:  http://localhost:8082
  order-service:    http://localhost:8083
  payment-service:  http://localhost:8086
