server:
  port: 8081

spring:
  application:
    name: customer-service
  config:
    import: "optional:configserver:http://config-admin:config-secret@localhost:8888"

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka:eureka-secret@localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.ecommerce.customer: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
    enabled: true
  show-actuator: false
